### ISSUE TITLE
Generate Global Enums

### ISSUE THREAD

**Issue by vendolis** [afterschoolstudio/Depot#49]
I am trying to use Depot for a card game. I have some Enum fields that are across different sheets, but I don't want to introduce issues with not updating one of the fields.  My current examples are "Illustrators" and "Set Icons", which are needed across all cards. 
I was trying to use the "Line Reference" but, I don't want to do lookups across sheets for this later in the code. (And while entering data the ID is hard to use to select the right line).
It would also be ok to have in a line reference the ability to select a field that is shown instead of the ID, to make the dropdown more readable.

**Comment by kkukshtel** [comment]
@vendolis why doesn't the Line Reference column work here for you? This is effectively what I use it for on some of my projects. Additionally, you can change the Line Reference "Display Column" in the settings for the sheet (that way you can point to some other top line column instead of the ID).

https://github.com/afterschoolstudio/Depot/wiki/Depot-Sheet-Information#sheet-config-options

**Comment by vendolis** [comment]
I am sorry. That is all I wanted. I missed that. I only saw that you can select Guid and Id... and did not think that at that point those are the only fields.
